language: cpp
sudo: false

script: mkdir build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=../arm.cmake -DBOARD=mpad6 && make

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - debian-sid
    packages:
    - cmake
    - cmake-data
    - gcc-arm-linux-gnueabihf
