language: cpp
sudo: required

script: mkdir build && cd build && cmake .. -DBOARD=mpad6 && make

addons:
  apt:
    sources:
    - &full_sources [george-edison55/precise-backports]
    packages:
    - &full_apt [cmake]
