language: cpp
sudo: false

script: mkdir build && cd build && cmake .. -DBOARD=mpad6 && make

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
